name: condorcet_vote
services:
  php:
    container_name: condorcet-vintage
    build: ./Docker/Web/.
    restart: always
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    # commentez la ligne suivante en production, elle permet d'avoir de beaux logs lisibles en dev
    tty: true
    networks:
      - condorcet-network
    depends_on:
      - mariadb
    environment:
      - SERVER_NAME=:80
      - CONDORCETDB_USER_PASSWORD=${CONDORCETDB_USER_PASSWORD}
      - CADDY_EXTRA_CONFIG=${CADDY_EXTRA_CONFIG}
  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - condorcetdb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${CONDORCETDB_ROOT_PASSWORD}
      - MYSQL_USER=condorcet_user
      - MYSQL_PASSWORD=${CONDORCETDB_USER_PASSWORD}
      - MYSQL_DATABASE=condorcet
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - condorcet-network

networks:
  condorcet-network: {}
  caddy-network:
    external: true

volumes:
  condorcetdb:
    external: true
  caddy_data:
  caddy_config:
